### ISSUE TITLE
JLCPCB DFM Issue: C9, C2 placed with wrong polarity

### ISSUE THREAD

**Issue by calotlea** [Onwrikbaar/NeoDK#6]
I just triggered a build with the latest JLCPCB files, the CPL file may need a 180 degree rotation for C9 and C2. See attached.

![Capacitor Polarity](https://github.com/user-attachments/assets/adced709-e15c-49ee-8d8d-4e2fce9883ec)

**Comment by Onwrikbaar** [comment]
This is a JLC layout viewer anomaly that I've seen before. All three capacitors have the same rotation in the CPL file. On ordering JLC will catch the error and either inquire about it or tacitly correct it.

Thank you for reporting it!
